### ISSUE TITLE
Forking Exception: Can't find PDO driver

### ISSUE THREAD

**Issue by phuze** [lifo101/php-daemon#12]
I am encountering a forking issue -- says PDO driver isn't found.

```
Error: Forking Exception: could not find driver in file: /var/www/api/daemons/projectX/OrderProcess.php on line: 65
Plain Stack Trace:
#0 /var/www/api/daemons/projectX/OrderProcess.php(65): PDO->__construct('sqlsrv:Server=l...', 'MY_USER', 'MY_PASS')
#1 [internal function]: OrderProcess->run()
#2 /var/www/api/vendor/lifo/php-daemon/src/Lifo/Daemon/Daemon.php(1593): call_user_func_array(Array, Array)
#3 [internal function]: Lifo\Daemon\Daemon->Lifo\Daemon\{closure}()
#4 /var/www/api/vendor/lifo/php-daemon/src/Lifo/Daemon/Plugin/ProcessManager.php(148): call_user_func_array(Object(Closure), Array)
#5 /var/www/api/vendor/lifo/php-daemon/src/Lifo/Daemon/Daemon.php(1612): Lifo\Daemon\Plugin\ProcessManager->fork('task', Object(Closure))
#6 /var/www/api/daemons/projectX/OrderDaemon.php(42): Lifo\Daemon\Daemon->task('OrderProcess')
#7 /var/www/api/vendor/lifo/php-daemon/src/Lifo/Daemon/Daemon.php(1746): OrderDaemon->execute()
#8 /var/www/api/vendor/lifo/php-daemon/src/Lifo/Daemon/Daemon.php(491): Lifo\Daemon\Daemon->loop()
#9 /var/www/api/daemons/projectX/run.php(15): Lifo\Daemon\Daemon->run()
#10 /var/www/api/daemon.php(33): {closure}()
#11 {main}
```

Line 65, as noted above, is this:

`$connection = new PDO($dsn, AZURE_SQL_USER, AZURE_SQL_PASS);`

I am using this driver elsewhere on the same server, so it is installed and working.

![php-sqlsrv](https://user-images.githubusercontent.com/9218035/39461673-7152ba7a-4cda-11e8-9466-a1ffa8cc7643.PNG)

![php-pdo](https://user-images.githubusercontent.com/9218035/39461374-21e36a0e-4cd8-11e8-8e54-dfb1b64bff2a.PNG)

Thoughts?

**Comment by phuze** [comment]
It occurred to me that this daemon executes php through the command line. I had these extensions enabled in the apache2 config `/etc/php/7.2/apache2/php.ini`, but not in the CLI config `/etc/php/7.2/cli/php.ini`.
